#ifndef APP_TASK_CFG_H
#define APP_TASK_CFG_H

#define TASK_APP_GPIONOTIF_NAME        "gpioNotif"
#define TASK_APP_GPIONOTIF_PRIORITY    53
#define TASK_APP_GPIONOTIF_STK_SIZE    256

#define TASK_APP_GPIOTOGGLE_NAME       "gpioToggle"
#define TASK_APP_GPIOTOGGLE_PRIORITY   54
#define TASK_APP_GPIOTOGGLE_STK_SIZE   256

#endif
